language: java

dist: trusty
sudo: required

addons:
    sonarcloud:
        organization: "lorenzorossi02"
        token:
            secure: "3d8f8eb3fb6e6f066b1a0ec83bbaa1bbfd44ac6e"
            
jdk:
- openjdk8
            
script: 
    - ant build
    - sonar-scanner