language: java
jdk:
- openjdk8

addons:
    sonarcloud:
        organization: "lorenzorossi02"
        token:
            secure: travis encrypt 3686844ff62c1c95f0f5f080623b593f3cf352ad
script: 
    - ant build
    - sonar-scanner