language: java

dist: trusty
sudo: required

addons:
    sonarcloud:
        organization: "lorenzorossi02"
        token:
            secure: "d7690fadb5641304aca7d0ba5703cf9087d73386"
            
jdk:
- openjdk8
            
script: 
    - ant build
    - sonar-scanner