language: java

dist: trusty
sudo: required

addons:
    sonarcloud:
        organization: "lorenzorossi02"
        token:
            secure: "76f563054b255278f91e403b4fc1865dfd7b2181"
            
jdk:
- openjdk8
            
script: 
    - ant build
    - sonar-scanner