language: java
jdk:
- openjdk8

dist: trusty

addons:
    sonarcloud:
        organization: "lorenzorossi02"
        token:
            secure: "2975c966faead9a7eb638b1cbf5c24cd910503e2"
script: 
    - ant build
    - sonar-scanner