language: java

addons:
  sonarcloud:
    organization: "lorenzorossi02"
    token:
        secure: "f24a3a9c180f23ae93244418bfb24993d21e3c2d"
            
jdk:
- openjdk8
            
script: 
    - ant build
    - sonar-scanner