language: java
jdk:
- openjdk8

dist: trusty

addons:
    sonarcloud:
        organization: "lorenzorossi02"
        token:
            secure: "112abfba13122894b59fc7e74eb92fe0cf8cd926"
            
script: 
    - ant build
    - sonar-scanner